### ISSUE TITLE
sacreblue.tokenizers v2.3.1没有TOKENIZERS

### ISSUE THREAD

**Issue by sxysxy** [DeepLearnXMU/RevisedKey-knn-mt#2]
参考您在Issue #1 中安装的2.3.1版sacrebleu：

<img width="552" alt="image" src="https://github.com/DeepLearnXMU/RevisedKey-knn-mt/assets/16396193/e72e805a-1a34-441e-b345-ca3264ff065c">

<img width="1244" alt="image" src="https://github.com/DeepLearnXMU/RevisedKey-knn-mt/assets/16396193/47852597-0596-4fb8-8ccf-80e4ee9b9ea2">

参考<a href=https://github.com/mjpost/sacrebleu/tree/v2.3.1/sacrebleu/tokenizers>sacrebleu仓库的tokenizers模块</a>，以及文件夹下的__init__.py，其中确实没有TOKENIZERS的定义。

报错的代码在RevisedKey-knn-mt/fairseq/scoring/tokenizer.py中

**Comment by czwlines** [comment]
你是在运行哪个脚本？

**Comment by sxysxy** [comment]
```bash knnmt_inference.sh base koran```

> 你是在运行哪个脚本？

**Comment by czwlines** [comment]
你试试 sacrebleu == 1.5.1

**Comment by sxysxy** [comment]
好的好的谢谢！可以运行了！！！

顺便：发现好像这个Infernce代码的实现对GPU的利用率不高的样子？top一看CPU占用100%，nvidia-smi GPU占用一直只在25%左右...

<img width="661" alt="image" src="https://github.com/DeepLearnXMU/RevisedKey-knn-mt/assets/16396193/1f6186c8-f6f8-448d-8a8d-3a4d2b72556b">

<img width="580" alt="image" src="https://github.com/DeepLearnXMU/RevisedKey-knn-mt/assets/16396193/802c4e16-e453-498f-ab8c-739a24768936">

总之非常感谢！！！终于跑起来了！！！

顺便我最近发现了一个repo，把多种KNNMT的实现整合到了一个框架里面，方便测试各种模型的效果，和研究新模型，https://github.com/NJUNLP/knn-box
Orz

**Comment by czwlines** [comment]
哈哈哈，没事，跑起来就好！GPU利用率不高的原因是：检索数据库时，需要把向量先转移到CPU，检索得到表示后再转移到GPU，用来计算概率。可以看这个 https://github.com/NJUNLP/knn-box/blob/master/knnbox/retriever/utils.py

knnbox 我也在用，但我当时做的时候它还没出来。我现在做的一个加速工作就是在它基础上实现的

**Comment by sxysxy** [comment]
好耶！

**Comment by sxysxy** [comment]
顺便又来打扰一下，https://github.com/NJUNLP/knn-box/issues/25 想讨论一下关于KNN检索导致的性能问题😂最近我也是在研究一些加速的工作，却发现好像KNN检索根本没那么慢...

**Comment by czwlines** [comment]
> 顺便又来打扰一下，[NJUNLP/knn-box#25](https://github.com/NJUNLP/knn-box/issues/25) 想讨论一下关于KNN检索导致的性能问题😂最近我也是在研究一些加速的工作，却发现好像KNN检索根本没那么慢...

在 faiss 只能用CPU时检索确实很慢（～10倍），但当可以用GPU后，速度就提上来了

**Comment by sxysxy** [comment]
嗯嗯，我想问的就是，原始KNMMT所说的，KNN索引导致变慢了2个数量级，有没有可能是因为原作者的代码GPU利用率不高导致的....我实在没能跑起来原版KNNMT的代码，它有个HOME环境变量不知道要设置成什么....就厚着脸皮来问问了QwQ
