### ISSUE TITLE
fairseq-vocab.txt 

### ISSUE THREAD

**Issue by Mchun-zhou** [DeepLearnXMU/RevisedKey-knn-mt#3]
VOCAB_PATH=${PROJECT_PATH}/models/wmt19.de-en/fairseq-vocab.txt
The fairseq-vocab.txt can not be found.Could you provide it.

**Comment by czwlines** [comment]
we use the same vocab with the pre-trained translation model from [this site](https://github.com/pytorch/fairseq/blob/master/examples/wmt19/README.md).

The `fairseq-vocab.txt` is rename from `dict.de.txt`.

**Comment by NCUIui** [comment]
你好我想请问一下在训练修改器时，没修改代码报错：
Traceback (most recent call last):
  File "..//revisedkey/train.py", line 314, in <module>
    main(args)
  File "..//revisedkey/train.py", line 266, in main
    trainer.train(train_dataloader, valid_dataloader)
  File "..//revisedkey/train.py", line 89, in train
    valid_state = self.validate(train_dataloader, valid_dataloader, epoch=epoch)
  File "..//revisedkey/train.py", line 138, in validate
    self.build_datastore(train_dataloader, epoch)
  File "..//revisedkey/train.py", line 215, in build_datastore
    self.save_datastore(train_dataloader, dstore_mmap)
  File "..//revisedkey/train.py", line 156, in save_datastore
    token.split(self.args.dstore_max_tokens, 0))):
ValueError: not enough values to unpack (expected 4, got 3)
这是什么原因？之前执行都没问题，谢谢。

**Comment by czwlines** [comment]
> 你好我想请问一下在训练修改器时，没修改代码报错： Traceback (most recent call last): File "..//revisedkey/train.py", line 314, in main(args) File "..//revisedkey/train.py", line 266, in main trainer.train(train_dataloader, valid_dataloader) File "..//revisedkey/train.py", line 89, in train valid_state = self.validate(train_dataloader, valid_dataloader, epoch=epoch) File "..//revisedkey/train.py", line 138, in validate self.build_datastore(train_dataloader, epoch) File "..//revisedkey/train.py", line 215, in build_datastore self.save_datastore(train_dataloader, dstore_mmap) File "..//revisedkey/train.py", line 156, in save_datastore token.split(self.args.dstore_max_tokens, 0))): ValueError: not enough values to unpack (expected 4, got 3) 这是什么原因？之前执行都没问题，谢谢。

see https://github.com/DeepLearnXMU/RevisedKey-knn-mt/issues/4#issue-1929882665
