### ISSUE TITLE
训练修改器时代码报错

### ISSUE THREAD

**Issue by NCUIui** [DeepLearnXMU/RevisedKey-knn-mt#4]
你好我想请问一下在训练修改器时，没修改代码报错：
Traceback (most recent call last):
File "..//revisedkey/train.py", line 314, in
main(args)
File "..//revisedkey/train.py", line 266, in main
trainer.train(train_dataloader, valid_dataloader)
File "..//revisedkey/train.py", line 89, in train
valid_state = self.validate(train_dataloader, valid_dataloader, epoch=epoch)
File "..//revisedkey/train.py", line 138, in validate
self.build_datastore(train_dataloader, epoch)
File "..//revisedkey/train.py", line 215, in build_datastore
self.save_datastore(train_dataloader, dstore_mmap)
File "..//revisedkey/train.py", line 156, in save_datastore
token.split(self.args.dstore_max_tokens, 0))):
ValueError: not enough values to unpack (expected 4, got 3)
这是什么原因？之前执行都没问题，谢谢。

**Comment by czwlines** [comment]
> 你好我想请问一下在训练修改器时，没修改代码报错： Traceback (most recent call last): File "..//revisedkey/train.py", line 314, in main(args) File "..//revisedkey/train.py", line 266, in main trainer.train(train_dataloader, valid_dataloader) File "..//revisedkey/train.py", line 89, in train valid_state = self.validate(train_dataloader, valid_dataloader, epoch=epoch) File "..//revisedkey/train.py", line 138, in validate self.build_datastore(train_dataloader, epoch) File "..//revisedkey/train.py", line 215, in build_datastore self.save_datastore(train_dataloader, dstore_mmap) File "..//revisedkey/train.py", line 156, in save_datastore token.split(self.args.dstore_max_tokens, 0))): ValueError: not enough values to unpack (expected 4, got 3) 这是什么原因？之前执行都没问题，谢谢。

just delete the `distance` in "revisedkey/train.py" line 156
